[package]
name = "comments-rs-memdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comments-rs-core = { path = "../comments-rs-core" }
tokio = { version = "1.15", features = ["full"] }